# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import importlib
import importlib.abc
import importlib.util
import marshal
import sys
import types
import base64
import zlib
import argparse
import subprocess
import threading
import time
import traceback
import cupy
import tkinter
import tkinter.filedialog
import tkinter.messagebox
import tkinter.scrolledtext
import tkinter.ttk
import gpuwebp.pipeline
import ntpath
import numpy
import PIL
import numba
import gpuwebp.vp8_encode
import shutil
import cupy.cuda
import cupy.cuda.compiler
import struct
import xml
import xml.sax
import xml.sax.saxutils
import re
import io
import PIL.Image
import imagecodecs
import json
import gpuwebp.closed_loop_jit