"""Generate vp8_tables.py by mechanically extracting constant tables from the
official libwebp C sources (BSD-licensed, webmproject/libwebp v1.5.0).
Run: python gen_tables.py  (from the gpuwebp package dir)
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT.parent / "vendor" / "libwebp-1.5.0"


def read(rel):
    return (SRC / rel).read_text(encoding="utf-8", errors="replace")


def extract_array(text, decl_regex, ndim):
    """Find `type name[...] = { ... };` and return nested python lists."""
    m = re.search(decl_regex, text, re.S)
    if not m:
        raise RuntimeError(f"cannot find: {decl_regex}")
    body = m.group(1)
    nums = [int(x) for x in re.findall(r"-?\d+", body)]
    dims = ndim
    if dims == 1:
        return nums
    if dims == 2:
        # split by rows: rely on known row length from the declaration
        raise NotImplementedError


def extract_flat(text, decl_regex, count, reshape=None):
    m = re.search(decl_regex, text, re.S)
    if not m:
        raise RuntimeError(f"cannot find: {decl_regex}")
    body = m.group(1)
    nums = [int(x) for x in re.findall(r"-?\d+", body)]
    # trailing '0  // sentinel' style comments are excluded by regex already
    if len(nums) < count:
        raise RuntimeError(f"expected {count} numbers, got {len(nums)}: {decl_regex}")
    nums = nums[:count]
    return nums


def nest(flat, shape):
    if len(shape) == 1:
        assert len(flat) == shape[0]
        return flat
    sub = len(flat) // shape[0]
    return [nest(flat[i * sub:(i + 1) * sub], shape[1:]) for i in range(shape[0])]


def main():
    tree_enc = read("src/enc/tree_enc.c")
    quant_enc = read("src/enc/quant_enc.c")
    frame_enc = read("src/enc/frame_enc.c")
    cost_enc = read("src/enc/cost_enc.c")
    cost_c = read("src/dsp/cost.c")
    filter_enc = read("src/enc/filter_enc.c")

    out = []
    out.append('"""VP8/WebP encoding constants extracted from libwebp v1.5.0 (BSD).')
    out.append("Generated by gen_tables.py -- do not edit by hand.")
    out.append('"""')
    out.append("import numpy as np\n")

    # VP8CoeffsProba0 [4][8][3][11]
    m = re.search(r"VP8CoeffsProba0\[NUM_TYPES\]\[NUM_BANDS\]\[NUM_CTX\]\[NUM_PROBAS\] = \{(.*?)\n\};",
                  tree_enc, re.S)
    v = [int(x) for x in re.findall(r"\d+", m.group(1))]
    assert len(v) == 4 * 8 * 3 * 11, len(v)
    out.append("COEFFS_PROBA0 = " + repr(nest(v, (4, 8, 3, 11))))

    # update-flag probabilities [4][8][3][11]
    m = re.search(r"VP8CoeffsUpdateProba\[NUM_TYPES\]\[NUM_BANDS\]\[NUM_CTX\]\[NUM_PROBAS\] = \{(.*?)\n\};",
                  tree_enc, re.S)
    v = [int(x) for x in re.findall(r"\d+", m.group(1))]
    assert len(v) == 4 * 8 * 3 * 11, len(v)
    out.append("COEFFS_UPDATE_PROBA = " + repr(nest(v, (4, 8, 3, 11))))

    # kBModesProba [10][10][9]
    m = re.search(r"kBModesProba\[NUM_BMODES\]\[NUM_BMODES\]\[NUM_BMODES - 1\] = \{(.*?)\n\};",
                  tree_enc, re.S)
    v = [int(x) for x in re.findall(r"\d+", m.group(1))]
    assert len(v) == 10 * 10 * 9, len(v)
    out.append("KF_BMODE_PROBA = " + repr(nest(v, (10, 10, 9))))

    # quant tables
    for name, pat, count, pyname in [
        ("kDcTable", r"kDcTable\[128\] = \{(.*?)\};", 128, "DC_TABLE"),
        ("kAcTable", r"kAcTable\[128\] = \{(.*?)\};", 128, "AC_TABLE"),
        ("kAcTable2", r"kAcTable2\[128\] = \{(.*?)\};", 128, "AC_TABLE2"),
    ]:
        m = re.search(pat, quant_enc, re.S)
        v = [int(x) for x in re.findall(r"\d+", m.group(1))]
        assert len(v) == count, (name, len(v))
        out.append(f"{pyname} = {v}")

    m = re.search(r"kBiasMatrices\[3\]\[2\] = \{(.*?)\};", quant_enc, re.S)
    v = [int(x) for x in re.findall(r"\d+", m.group(1))]
    assert len(v) == 6
    out.append("BIAS_MATRICES = " + repr(nest(v, (3, 2))))

    m = re.search(r"kFreqSharpening\[16\] = \{(.*?)\};", quant_enc, re.S)
    v = [int(x) for x in re.findall(r"\d+", m.group(1))]
    assert len(v) == 16
    out.append("FREQ_SHARPENING = " + str(v))

    # zigzag + bands (skip sentinel)
    out.append("ZIGZAG = [0, 1, 4, 8, 5, 2, 3, 6, 9, 12, 13, 10, 7, 11, 14, 15]")
    m = re.search(r"VP8EncBands\[16 \+ 1\] = \{(.*?)\};", cost_c, re.S)
    v = [int(x) for x in re.findall(r"\d+", m.group(1))][:16]
    out.append("ENC_BANDS = " + str(v))

    # categories
    m = re.search(r"VP8Cat3\[\] = \{(.*?)\};", frame_enc, re.S)
    out.append("CAT3 = " + str([int(x) for x in re.findall(r"\d+", m.group(1))]))
    m = re.search(r"VP8Cat4\[\] = \{(.*?)\};", frame_enc, re.S)
    out.append("CAT4 = " + str([int(x) for x in re.findall(r"\d+", m.group(1))]))
    m = re.search(r"VP8Cat5\[\] = \{(.*?)\};", frame_enc, re.S)
    out.append("CAT5 = " + str([int(x) for x in re.findall(r"\d+", m.group(1))]))
    m = re.search(r"VP8Cat6\[\] =\s*\n?\s*\{(.*?)\};", frame_enc, re.S)
    out.append("CAT6 = " + str([int(x) for x in re.findall(r"\d+", m.group(1))]))

    # entropy cost table
    m = re.search(r"VP8EntropyCost\[256\] = \{(.*?)\};", cost_c, re.S)
    v = [int(x) for x in re.findall(r"\d+", m.group(1))]
    assert len(v) == 256, len(v)
    out.append("ENTROPY_COST = " + str(v))

    # mode fixed costs
    m = re.search(r"VP8FixedCostsUV\[4\] = \{(.*?)\};", cost_enc, re.S)
    out.append("FIXED_COSTS_UV = " + str([int(x) for x in re.findall(r"\d+", m.group(1))]))
    m = re.search(r"VP8FixedCostsI16\[4\] = \{(.*?)\};", cost_enc, re.S)
    out.append("FIXED_COSTS_I16 = " + str([int(x) for x in re.findall(r"\d+", m.group(1))]))
    m = re.search(r"VP8FixedCostsI4\[NUM_BMODES\]\[NUM_BMODES\]\[NUM_BMODES\] = \{(.*?)\n\};",
                  cost_enc, re.S)
    v = [int(x) for x in re.findall(r"\d+", m.group(1))]
    assert len(v) == 1000, len(v)
    out.append("FIXED_COSTS_I4 = " + repr(nest(v, (10, 10, 10))))

    # filter strength table row for sharpness=0 (0..63 linear)
    m = re.search(r"kLevelsFromDelta\[8\]\[MAX_DELTA_SIZE\] = \{(.*?)\n\};",
                  filter_enc, re.S)
    v = [int(x) for x in re.findall(r"\d+", m.group(1))]
    # first 64 entries = sharpness 0 row
    row0 = v[:64]
    assert row0 == list(range(64)), row0
    out.append("FILTER_LEVEL_FROM_DELTA_SHARP0 = " + str(row0))

    out.append("""
# YUV conversion (BT.601, libwebp fixed point, YUV_FIX=16)
YUV_FIX = 16
YUV_HALF = 1 << (YUV_FIX - 1)

def rgb_to_y(r, g, b, rnd):
    luma = 16839 * r + 33059 * g + 6420 * b
    return (luma + rnd + (16 << YUV_FIX)) >> YUV_FIX

def _clip_uv(u, rnd):
    v = (u + rnd + (128 << YUV_FIX)) >> YUV_FIX
    return 0 if v < 0 else (255 if v > 255 else v)

def rgb_to_u(r, g, b, rnd):
    return _clip_uv(-9719 * r - 19081 * g + 28800 * b, rnd)

def rgb_to_v(r, g, b, rnd):
    return _clip_uv(28800 * r - 24116 * g - 4684 * b, rnd)
""")

    (ROOT / "vp8_tables.py").write_text("\n".join(out), encoding="utf-8")
    print("vp8_tables.py written,", len("\n".join(out)), "bytes")


if __name__ == "__main__":
    main()
